config/routes.rb
FsGoalplanner::Application.routes.draw do

  get "static_pages/help"
  get "static_pages/goal_show"
  get "static_pages/goal_graph"
  get "home/index"
  get 'task/:id' => 'tasks#completed', :as => :completed_task
  devise_for :users
  resources :users

  resources :people
  resources :goal_steps
  resources :goals do
    resources :milestones
  end

  resources :milestones do
    resources :tasks
  end

  resources :tasks

  namespace :admin do
    resources :templates
    resources :startups
    resources :users
  end

  root :to => 'home#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :email, :first_name, :is_active, :last_name
  belongs_to :startup
  has_many :tasks
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_filter :authenticate_user!
  # TODO: add default startup_id of the one belonging to the current_user
  # GET /people
  # GET /people.json
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= render "layouts/separator-header", :separator_title => "edit team member" %>

<div class="table-box small padded">
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :is_active %><br />
    <%= f.check_box :is_active %>
  </div>
  <div class="actions">
    <%= link_to_submit 'save', :id => "link_to_submit", :class => "fs-link link_to_submit" %>
    <%= link_to 'cancel', @person, :id => "cancel", :class => "fs-link link_to_submit" %>
  </div>
<% end %>
    <%= link_to 'back to list', people_path, :class => "fs-link left" %>
</div>

app/views/people/edit.html.erb
<%= render 'layouts/app-title' %>
<%= render 'layouts/new-form', :new_model => @person %>

app/views/people/index.html.erb
<%= render 'layouts/app-title' %>
<%= render "layouts/separator-header", :separator_title => "team members" %>

<div class="table-box medium padded">
  <table class="table" id="goalList">
  <tr>
    <th>name</th>
    <th>email</th>
    <th>active?</th>
  </tr>

<% @people.each do |person| %>
  <tr>
    <td><%= link_to person.full_name, person %></td>
    <td><%= person.email %></td>
    <td><%= person.is_active %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'add team member', new_person_path, :class => "fs-link" %>
</div>

app/views/people/new.html.erb
<%= render 'layouts/app-title' %>
<%= render 'layouts/new-form', :new_model => @person %>

app/views/people/show.html.erb
<%= render 'layouts/app-title' %>
<%= render "layouts/separator-header", :separator_title => "users" %>

<div class="table-box medium padded">
  <p id="notice"><%= notice %></p>

  <p>
    <b>First name:</b>
    <%= @person.first_name %>
  </p>

  <p>
    <b>Startup ID:</b>
    <%= @person.startup_id %>
  </p>

  <p>
    <b>Last name:</b>
    <%= @person.last_name %>
  </p>

  <p>
    <b>Email:</b>
    <%= @person.email %>
  </p>

  <p>
    <b>Is active:</b>
    <%= @person.is_active %>
  </p>

  <div class="dialog_links">
    <%= link_to 'edit', edit_person_path(@person), :class => "fs-link" %>
    <%= link_to 'delete', @person, :class => "fs-link", method: :delete, data: { confirm: 'Are you sure?' } %>
    <%= link_to 'back to list', people_path, :class => "fs-link left" %>
  </div>
</div>