Archive/config/routes.rb
FsGoalplanner::Application.routes.draw do

  get "static_pages/help"
  get "static_pages/goal_show"
  get "static_pages/goal_graph"
  get "home/index"

  devise_for :users
  resources :users

  resources :people
  resources :goal_steps
  resources :goals do
    resources :milestones
  end

  resources :milestones do
    resources :tasks
  end

  resources :tasks

  namespace :admin do
    resources :templates
    resources :startups
    resources :users
  end

  root :to => 'home#index'

end

Archive/app/models/startup.rb
class Startup < ActiveRecord::Base
  attr_accessible :founder, :founder_email, :name
  has_many :milestones, :dependent => :destroy
  has_many :people, :users
end

Archive/app/controllers/startups_controller.rb
class StartupsController < ApplicationController
  before_filter :authenticate_user!
  # GET /startups
  # GET /startups.json
  def index
    @startups = Startup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @startups }
    end
  end

  # GET /startups/1
  # GET /startups/1.json
  def show
    @startup = Startup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @startup }
    end
  end

  # GET /startups/new
  # GET /startups/new.json
  def new
    @startup = Startup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @startup }
    end
  end

  # GET /startups/1/edit
  def edit
    @startup = Startup.find(params[:id])
  end

  # POST /startups
  # POST /startups.json
  def create
    @startup = Startup.new(params[:startup])

    respond_to do |format|
      if @startup.save
        format.html { redirect_to @startup, notice: 'Startup was successfully created.' }
        format.json { render json: @startup, status: :created, location: @startup }
      else
        format.html { render action: "new" }
        format.json { render json: @startup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /startups/1
  # PUT /startups/1.json
  def update
    @startup = Startup.find(params[:id])

    respond_to do |format|
      if @startup.update_attributes(params[:startup])
        format.html { redirect_to @startup, notice: 'Startup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @startup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /startups/1
  # DELETE /startups/1.json
  def destroy
    @startup = Startup.find(params[:id])
    @startup.destroy

    respond_to do |format|
      format.html { redirect_to startups_url }
      format.json { head :no_content }
    end
  end
end

Archive/app/helpers/startups_helper.rb
module StartupsHelper
end

Archive/app/views/startups/_form.html.erb
<%= form_for(@startup) do |f| %>
  <% if @startup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@startup.errors.count, "error") %> prohibited this startup from being saved:</h2>

      <ul>
      <% @startup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :founder %><br />
    <%= f.text_field :founder %>
  </div>
  <div class="field">
    <%= f.label :founder_email %><br />
    <%= f.text_field :founder_email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Archive/app/views/startups/edit.html.erb
<%= render 'layouts/app-title' %>
<%= render 'form' %>

<%= link_to 'Show', @startup %> |
<%= link_to 'Back', startups_path %>

Archive/app/views/startups/index.html.erb
<%= render 'layouts/app-title' %>
<table>
  <tr>
    <th>Name</th>
    <th>Founder</th>
    <th>Founder email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @startups.each do |startup| %>
  <tr>
    <td><%= startup.name %></td>
    <td><%= startup.founder %></td>
    <td><%= startup.founder_email %></td>
    <td><%= link_to 'Show', startup %></td>
    <td><%= link_to 'Edit', edit_startup_path(startup) %></td>
    <td><%= link_to 'Destroy', startup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Startup', new_startup_path %>

Archive/app/views/startups/new.html.erb
<%= render 'layouts/app-title' %>
<%= render 'form' %>

Archive/app/views/startups/show.html.erb
<%= render 'layouts/app-title' %>
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @startup.name %>
</p>

<p>
  <b>Founder:</b>
  <%= @startup.founder %>
</p>

<p>
  <b>Founder email:</b>
  <%= @startup.founder_email %>
</p>


<%= link_to 'Edit', edit_startup_path(@startup) %> |
<%= link_to 'Back', startups_path %>