Archive/config/routes.rb
FsGoalplanner::Application.routes.draw do

  get "static_pages/help"
  get "static_pages/goal_show"
  get "static_pages/goal_graph"
  get "home/index"

  devise_for :users
  resources :users

  resources :people
  resources :goal_steps
  resources :goals do
    resources :milestones
  end

  resources :milestones do
    resources :tasks
  end

  resources :tasks

  namespace :admin do
    resources :templates
    resources :startups
    resources :users
  end

  root :to => 'home#index'

end

Archive/app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

=begin
  validates :password, :length => {
    :in => 6..20
    :too_short => "password must have at least 6 characters"
    :too_long => "password must have no more than 20 characters"
  }
=end

  # attr_accessible :title, :body
end

Archive/app/models/goal.rb
class Goal < ActiveRecord::Base
  attr_accessible :description, :due_on, :is_complete, :title, :is_template, :short_title, :milestones_attributes, :tasks_attributes
  has_many :milestones
  accepts_nested_attributes_for :milestones

  has_many :tasks, :through => :milestones
  accepts_nested_attributes_for :tasks

  belongs_to :startup

  scope :not_template,  :conditions => { :is_template => false }
  scope :is_template,  :conditions => { :is_template => true }
  scope :not_complete,  :conditions => { :is_complete => false }
  scope :is_complete,  :conditions => { :is_complete => true }

  scope :by_startup, lambda { |startup_id| { :conditions => { :startup_id => startup_id }}}

  validate :startup_id, :presence => true
  validate :title, :presence => true

end

Archive/app/models/milestone.rb
class Milestone < ActiveRecord::Base
  attr_accessible :description, :due_on, :goal_id, :is_complete, :order, :title, :percent_complete, :tasks_attributes
  belongs_to :goal
  has_many :tasks
  accepts_nested_attributes_for :tasks

  scope :not_template,  :conditions => { :is_template => false }
  scope :is_template,  :conditions => { :is_template => true }
  scope :not_complete,  :conditions => { :is_complete => false }
  scope :is_complete,  :conditions => { :is_complete => true }

  validate :goal_id, :presence => true
  validate :title, :presence => true
end

Archive/app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :email, :first_name, :is_active, :last_name
  belongs_to :startup
  has_many :tasks

  def initialize(attributes={})
    @firstname = attributes[:first_name]
    @lastname = attributes[:last_name]
  end

  # TODO: fix this
  def full_name
    return "#{@firstname} #{@lastname} -- method runs - doesn't return name"
  end
end

Archive/app/models/startup.rb
class Startup < ActiveRecord::Base
  attr_accessible :founder, :founder_email, :name
  has_many :milestones, :dependent => :destroy
  has_many :people, :users
end

Archive/app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :description, :due_on, :is_complete, :milestone_id, :order, :person_id, :title, :short_title
  belongs_to :milestone
  belongs_to :person

  validate :milestone_id, :presence => true
  validate :title, :presence => true

end

Archive/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :is_admin, :password, :person_id, :user_name
  belongs_to :startup
end

Archive/app/models/user_bak.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :role, :startup_id, :user_name
end

Archive/app/controllers/ajax_controller.rb
class AjaxController < ApplicationController

  respond_to :js

  def complete_task
    @task = Task.where(:id => params[:id])
    @task.is_complete = true
  end

end

Archive/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

Archive/app/helpers/ajax_helper.rb
module AjaxHelper
end

Archive/app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_submit(*args, &block)
    link_to_function (block_given? ? capture(&block) : args[0]), "$(this).closest('form').submit()", args.extract_options!
  end
end

Archive/app/helpers/goals_helper.rb
module GoalsHelper
end

Archive/app/helpers/home_helper.rb
module HomeHelper
end

Archive/app/helpers/milestones_helper.rb
module MilestonesHelper
end

Archive/app/helpers/people_helper.rb
module PeopleHelper
end

Archive/app/helpers/startups_helper.rb
module StartupsHelper
end

Archive/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

Archive/app/helpers/tasks_helper.rb
module TasksHelper
end

Archive/app/helpers/users_helper.rb
module UsersHelper
end

Archive/app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

Archive/app/views/layouts/_app-title.html.erb
<div class="page-title">
<!--   <%= image_tag "app-logo.png", :class => "app-logo" %><br /> -->
  goal planner
</div>

Archive/app/views/layouts/_menu-bar.html.erb
<div class="navbar navbar-center">
  <div class="navbar-inner">
    <ul class="nav nav-pointer">
      <li>
          <%= link_to 'start a new goal', new_goal_path %>
      </li>
      <li>
          <%= link_to 'review goals', goals_path %>
      </li>
      <li>
          <%= link_to 'review milestones', milestones_path %>
      </li>
      <li>
          <%= link_to 'review tasks', tasks_path %>
      </li>
      <li>
        <div class="hidden"><%= link_to 'review team activity', people_path %></div>
      </li>
    <%= if current_user.try(:is_admin?) then ( %>
      <li>
        <%= link_to 'add/edit users', users_path %>
      </li>
    <%= ) end %>
    </ul>
  </div>
</div>

Archive/app/views/layouts/_new-form.html.erb
<%= render "layouts/separator-header", :separator_title => "#{new_model.title}" %>

<div class="table-box small padded">

<%= form_for(new_model) do |f| %>
  <% if new_model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(new_model.errors.count, "error") %> prohibited this model from being saved:</h2>
      <ul>
      <% new_model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :is_complete %>
    <%= f.check_box :is_complete %>
  </div>
  <%= if current_user.try(:is_admin?) then ( %>
  <div class="field">
    <%= f.label :is_template %>
    <%= f.check_box :is_template %>
  </div>
  <%= ) end %>
  <div class="field">
    <%= f.label :due_on %><br />
    <%= f.text_field :due_on, :id => :datepicker %>
  </div>
  <div class="actions">
    <%= link_to_submit 'save', :id => "link_to_submit", :class => "fs-link link_to_submit" %>
    <%= link_to 'cancel', @milestone, :id => "cancel", :class => "fs-link link_to_submit" %>
  </div>
<% end %>

Archive/app/views/layouts/_separator-header.html.erb
<h3 class="separator-header"><span><%= separator_title %></span></h3>

Archive/app/views/layouts/_site-banner.html.erb
<div role="banner" class="main-header">
  <div class="wrapper">
    <div class="row-fluid">
      <div class="span4">
      <%= link_to(image_tag("logo-temp.png", :alt => "foundersuite logo", :title => "Click here to return to Home"), "/") %>
      </div>
      <div class="user-opt span5 offset3">
        <% if user_signed_in? %>
        <div class="login_user"><%= current_user.user_name %></div>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete, :class => "btn-info btn") %>
        <% else %>
          <%= link_to('Login', new_user_session_path, :class => "btn-info btn" )  %>
        <% end %>
      </div>
    </div>
  </div>
</div>

Archive/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foundersuite | startup management software</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/site-banner' %>
<%= render 'layouts/menu-bar' %>

<%= yield %>

</body>
</html>